M = {}

M.config = {
  -- The register to use for saving the link which generated by the plugin
  register = "+",

  -- Methods of detecting the root directory.
  -- if one is not detected, the other is used as fallback. You can also delete or rearangne the detection methods.
  detection_methods = { "pattern", "lsp" },
  -- All the patterns used to detect root dir, when **"pattern"** is in
  -- detection_methods
  patterns = { ".git", "_darcs", ".hg", ".bzr", ".svn", "package.json" },

  -- Table of lsp clients to ignore by name
  -- eg: { "efm", ... }
  ignore_lsp = {},
}

M.init = function(params)
  M.config = vim.tbl_deep_extend("force", M.config, params or {})
end

return M
