M = {}

M.config = {
	-- The register to use for saving the link which generated by the plugin
	register = "+",
}

M.init = function(params)
	M.config = vim.tbl_deep_extend("force", M.config, params or {})
end

return M
